### ISSUE TITLE
Problem z gminą Łańcut @iMPA

### ISSUE THREAD

**Issue by zibik** [wiktorn/osm-addr-tools#20]
./punktyadresowe_import.py lancut
INFO:__main__.iMPA:http://lancut.e-mapa.net/application/system/init.php
Traceback (most recent call last):
  File "./punktyadresowe_import.py", line 667, in <module>
    main()
  File "./punktyadresowe_import.py", line 644, in main
    rets = parallel_execution(*map(lambda x: lambda: imp_gen(x).getAddresses(), args.gmina))
  File "/home/zibi/osm-tools/impa/osm-addr-tools/utils.py", line 12, in parallel_execution
    [__executor.submit(x) for x in args]
  File "/home/zibi/osm-tools/impa/osm-addr-tools/utils.py", line 11, in <lambda>
    map(lambda x: x.result(),
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./punktyadresowe_import.py", line 644, in <lambda>
    rets = parallel_execution(*map(lambda x: lambda: imp_gen(x).getAddresses(), args.gmina))
  File "./punktyadresowe_import.py", line 378, in __init__
    self._initFromIMPA(gmina)
  File "./punktyadresowe_import.py", line 395, in _initFromIMPA
    init_data = json.loads(data)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 3760 (char 3759)

**Comment by wiktorn** [comment]
To wynika z tego, że:
http://lancut.e-mapa.net/application/system/init.php

Nie jest poprawnym JSON-em (np. http://jsonlint.com/ pokaże, że):
                {
                    "value": "63",
                    "text": "MPZP 013, uchwała XXXIV/219/97",
                    "data": [
                        ,
                        ,
                        ,
                        
                    ]
                },

Nie może być tak, że mamy strukturę [, , ,].

Poszukam jakby takie błędy obejść. Można spróbować też to poprawić u źródła, lub po prostu podać --wms i --terc.

**Comment by wiktorn** [comment]
Ostatnia poprawka adresuje również ten błąd.
