### ISSUE TITLE
Problem z gminą Zduńska Wola

### ISSUE THREAD

**Issue by zibik** [wiktorn/osm-addr-tools#30]
./merger.py --gugik --terc  1019042
[CUT]
```
INFO:__main__:Working with TERC: 1019042
INFO:__main__:Processing 3808 addresses
Traceback (most recent call last):
  File "./merger.py", line 830, in <module>
    main()
  File "./merger.py", line 817, in main
    m = Merger(data, addr, terc, source_addr)
  File "./merger.py", line 257, in __init__
    self.osmdb = OsmDb(self.asis, valuefunc=from_soup, indexes={'address': lambda x: x.get_index_key(), 'id': lambda x: x.osmid})
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 163, in __init__
    self.__osm_obj = dict(((x['type'], x['id']), OsmDbEntry(self._valuefunc(x), x, self)) for x in self._osmdata['elements'])
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 163, in <genexpr>
    self.__osm_obj = dict(((x['type'], x['id']), OsmDbEntry(self._valuefunc(x), x, self)) for x in self._osmdata['elements'])
  File "./merger.py", line 84, in from_soup
    soup        = obj
  File "./merger.py", line 49, in __init__
    super(OsmAddress, self).__init__(*args, **kwargs)
  File "/home/zibi/osm-tools/impa/osm-addr-tools/punktyadresowe_import.py", line 146, in __init__
    assert not street or street == street.strip()
AssertionError
```

**Comment by wiktorn** [comment]
Ten budynek był źródłem kłopotów:
http://www.openstreetmap.org/way/287946102
