### ISSUE TITLE
Sudziałowo

### ISSUE THREAD

**Issue by zibik** [wiktorn/osm-addr-tools#32]
./merger.py --impa sudzialowo
INFO:punktyadresowe_import.iMPA:http://sudzialowo.e-mapa.net/application/system/init.php
Traceback (most recent call last):
  File "./merger.py", line 875, in <module>
    main()
  File "./merger.py", line 809, in main
    imp = iMPA(args.impa, wms=args.wms)
  File "/home/zibi/osm-tools/impa/osm-addr-tools/punktyadresowe_import.py", line 399, in __init__
    self._initFromIMPA(gmina)
  File "/home/zibi/osm-tools/impa/osm-addr-tools/punktyadresowe_import.py", line 432, in _initFromIMPA
    self.setBboxFrom2180(init_data['spatialExtent'])
KeyError: 'spatialExtent'

**Comment by zibik** [comment]
Ech, ślepy jestem i niepotrzebnie zawracałem głowę. Chodziło o gminę Szudziałowo, a ja myślałem, że jakiś błąd jest.
Dzięki i sorry za kłopot.
