### ISSUE TITLE
Iłża - ./merger.py --impa ilza

### ISSUE THREAD

**Issue by zibik** [wiktorn/osm-addr-tools#34]
INFO:__main__:Working with TERC: 142503
INFO:__main__:Processing 4034 addresses
Traceback (most recent call last):
  File "./merger.py", line 914, in <module>
    main()
  File "./merger.py", line 901, in main
    m = Merger(data, addr, terc, source_addr)
  File "./merger.py", line 295, in __init__
    self._import_area_shape = get_boundary_shape(terc)
  File "./merger.py", line 778, in get_boundary_shape
    osmdb = OsmDb(soup)
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 164, in __init__
    self.update_index()
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 174, in update_index
    pos = self.get_shape(val._raw).centroid
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 212, in get_shape
    ret = self.get_shape_cached(soup)
  File "/home/zibi/osm-tools/impa/osm-addr-tools/osmdb.py", line 253, in get_shape_cached
    for member in filter(lambda x: x['type'] == 'way', soup['members']):
KeyError: 'members'

**Comment by wiktorn** [comment]
Problem jest z relacją:
http://www.openstreetmap.org/relation/2421729

Nie ma żadnego członka. Właśnie wrzuciłem poprawkę - ab3e4d2d38638d0570ae5e624d138430c705ea4f i będzie zgłaszany jasny błąd, która relacja wymaga poprawy.
